book/book/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('management', include('management.urls')),
    path('auth', include('user.urls')),
    path('csv', include('csvs.urls')),
    path('excel', include('excel.urls')),
    # path('pdfs', include('pdfs.urls')),
]

book/csvs/urls.py
from django.urls import path
from .views import csv_read, csv_read_dic, csv_write, csv_write_dic

# app_name = 'user'
urlpatterns = [
    path('/read', csv_read, name='read'),
    path('/dread', csv_read_dic, name='dread'),
    path('/write', csv_write, name='write'),
    path('/dwrite', csv_write_dic, name='dwrite'),
]

book/excel/urls.py
from django.urls import path
from .views import excel_writer, excel_reader

# app_name = 'user'
urlpatterns = [
    path('/write', excel_writer, name='write'),
    path('/read', excel_reader, name='read'),
]

book/management/urls.py
from django.urls import path
from .views import BookSaveFormView, BookSaveFormSuccessView, BookUpdateFormView, BookCreateFormView, BookDeleteFormView, BookDetailFormView, BookListFormView

app_name = 'management'
urlpatterns = [
    path('/save/', BookSaveFormView.as_view(), name='save'),
    path('/', BookListFormView.as_view(), name='index'),
    path('/create/', BookCreateFormView.as_view(), name='create'),
    path('/detail/<int:pk>', BookDetailFormView.as_view(), name='show'),
    path('/update/<int:pk>', BookUpdateFormView.as_view(), name='update'),
    path('/delete/<int:pk>', BookDeleteFormView.as_view(), name='delete'),
    path('/save/success', BookSaveFormSuccessView.as_view(), name='book_success_message'),
    # path('update/<int:id>', views.update, name='update'),
    # path('delete/<int:id>', views.delete, name='delete'),
]

book/user/urls.py
from django.urls import path
from .views import UserLoginView, UserLogoutView, UserPasswordChangeView, UserPasswordResetView

# app_name = 'user'
urlpatterns = [
    path('/login', UserLoginView.as_view(), name='login'),
    path('/logout', UserLogoutView.as_view(), name='logout'),
    path('/change-password', UserPasswordChangeView.as_view(), name='change_password'),
    path('/password-reset', UserPasswordResetView.as_view(), name='password_reset'),
    # path('/save/', BookSaveFormView.as_view(), name='save'),
    # path('update/<int:id>', views.update, name='update'),
    # path('delete/<int:id>', views.delete, name='delete'),
]

book/csvs/models.py
from django.db import models

# Create your models here.

book/excel/models.py
from django.db import models

# Create your models here.

book/management/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    name = models.CharField(max_length=255)
    author = models.CharField(max_length=80)

book/management/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'author']

book/csvs/views.py
from django.shortcuts import render
from django.views.generic import ListView
import csv

# Create your views here.
def csv_read(request):
    filename="documents\Libro1.csv"
    try:
        with open(filename) as file:
            csv_reader = csv.reader(file, delimiter=";")
            response = render(request, 'csv.html', {'objects': csv_reader})
        # file.close()
            return response
    except (IOError) as error:
        print("Error {}".format(error))

def csv_read_dic(request):
    filename="documents\Libro1.csv"
    try:
        file = open(filename)
        csv_reader = csv.DictReader(file, delimiter=";")
        response = render(request, 'csv.html', {'objects': csv_reader})
        file.close()
        return response
    except (IOError) as error:
        print("Error {}".format(error))

def csv_write(request):
    filename="documents\Libro2.csv"
    try:
        file = open(filename, 'w', newline='')
        csv_writer = csv.writer(file, delimiter=",")
        print(type(csv_writer))
        csv_writer.writerow(['Movie 1', 'Movie 2', 'Movie 3'])
        csv_writer.writerow(['Avengers', 'EndGame', 'Toy Story 3'])
        return render(request, 'csv.html', {'objects': []})
    except (IOError) as error:
        print("Error {}".format(error))

def csv_write_dic(request):
    filename="documents\Libro2.csv"
    try:
        file = open(filename, 'w', newline='')
        csv_writer = csv.DictWriter(file, delimiter=",", fieldnames=['name','surname'])
        print(type(csv_writer))
        csv_writer.writeheader()
        csv_writer.writerow({ 'name': 'Andres', 'surname': 'Cruz'})
        return render(request, 'csv.html', {'objects': []})
    except (IOError) as error:
        print("Error {}".format(error))

book/excel/views.py
from django.shortcuts import render
import xlsxwriter
import openpyxl

# Create your views here.
def excel_writer(request):
    filename = "documents/LibroExcel3.xlsx"

    data = [
        ["Name", "Surname", "Age"],
        ["Jon", "Snow", 33],
        ["Daenerys", "Targaryen", 25],
        ["Tyrion", "Lannister", 40],
        ["Jaime", "Lannister", 35],
        ["Cersei", "Lannister", 36]
    ]

    workbook = xlsxwriter.Workbook(filename)
    worksheet = workbook.add_worksheet("Hojax 1")

    for row in range(len(data)):
        for col in range(len(data[row])):
            worksheet.write(row, col, data[row][col])

    workbook.close()

    return render(request, "csv.html")

def excel_reader(request):
    filename = "documents/LibroExcel.xlsx"

    workbook = openpyxl.load_workbook(filename)
    worksheet = workbook.active

    for row in range(worksheet.max_row):
        for col in worksheet.iter_cols(row, worksheet.max_column):
            print( col[row].value, end="\t")
            print('')

    workbook.close()
    return render(request, "csv.html")

book/management/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse
from django.views.generic.edit import FormView, UpdateView, CreateView, DeleteView
from django.views.generic import DetailView, ListView
from .forms import BookForm
from .models import Book

# Create your views here.
#Vista básica para creación con un formulario específico
class BookSaveFormView(FormView):
    template_name = 'book/save.html'
    form_class = BookForm
    success_url = '/management/save/success'

    # This is what we have to handle before actually saving the record
    def form_valid(self, form):
        form.save()
        return super().form_valid(form) # Actually save the record

#Vista básica para creación
class BookCreateFormView(CreateView):
    model=Book
    template_name = 'book/save.html'
    form_class = BookForm
    # fields = ['name',] # Es posible seleccionar solo los campos que se desean editar, peor hay que quitar form_class
    success_url = '/management/save/success'

#Vista básica para edición
class BookUpdateFormView(UpdateView):
    model=Book
    template_name = 'book/save.html'
    form_class = BookForm
    # fields = ['name',] # Es posible seleccionar solo los campos que se desean editar, peor hay que quitar form_class
    success_url = '/management/save/success'

#Vista básica para el detalle
class BookDetailFormView(DetailView):
    model=Book
    template_name = 'book/detail.html'
    #Opcional
    context_object_name = 'libro' # Para cambiar el nombre "object" o "book" que recibe el template

#Vista básica para eliminacion
class BookDeleteFormView(DeleteView):
    model=Book
    template_name = 'book/delete.html'
    success_url = '/management/save/success'

#Vista básica para lista de libros
class BookListFormView(ListView):
    model=Book
    template_name = 'book/index.html'

# Vista básica para consulta
class BookSaveFormSuccessView(View):
    def get(self, request):
        return HttpResponse('El libro se creó')

book/user/views.py
from django.shortcuts import render

from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetView

class UserLoginView(LoginView):
    template_name="login.html"
    next_page="/management/"
    redirect_authenticated_user=True
    # extra_context={
    #     'key1':"valor 1",
    #     'key2':"valor 2",
    # }

class UserLogoutView(LogoutView):
    next_page="/auth/login"


class UserPasswordChangeView(PasswordChangeView):
    template_name="password-change.html"
    next_page="/auth/login"


class UserPasswordResetView(PasswordResetView):
    template_name="reset-password.html"

book/csvs/templates/csv.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CSV</title>
</head>
<body>
  <h1>CSV Manager</h1>

    <table>
        {% for l in objects %}
            <tr>
                {% for r in l %}
                    <td>{{ r }}</td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
</body>
</html>

book/management/templates/book/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        Seguro que quieres borrar el registro
        <input type="submit" value="Eliminar">
    </form>
</body>
</html>

book/management/templates/book/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
    <h3>{{ libro.name }}</h3>
    <p>{{ object.author }}</p>
</body>
</html>

book/management/templates/book/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista</title>
</head>
<body>
    <form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit">logout</button>
    </form>
    <hr>
    {% for b in book_list %}
        <p> {{ b.name }} </p>
    {% endfor %}
</body>
</html>

book/management/templates/book/save.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Save</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Save">
    </form>
</body>
</html>

book/user/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Login">
    </form>
</body>
</html>

book/user/templates/password-change.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Enviar</button>
    </form>
</body>
</html>

book/user/templates/reset-password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Enviar</button>
    </form>
</body>
</html>